spring:
  profiles:
    active: prod
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url:jdbc:h2:mem:testdb
server:
  port: 8081
---
spring:
  profiles: prod
  jpa:
    generate-ddl: true
    database: MYSQL
    show-sql: false

  datasource:
    username: user
    password: pass
    url: jdbc:mysql://172.17.0.2:3306/regulations

server:
  port: 8081